import 'package:project1/data_modle.dart';

List<DataModel> data = [
  DataModel(
    name: "Green tea",
    type: "Signaturs product",
    image: "images/greentea.png",
    price: 36,
    size: 500,
    id: 0,
    numberItemInCart: 1,
    cartFlag: false,
  ),
  DataModel(
    name: "Rose tea",
    type: "Signaturs product",
    image: "images/greentea.png",
    price: 24,
    size: 500,
    id: 1,
    numberItemInCart: 1,
    cartFlag: false,
  ),
  DataModel(
    name: "Jasmine tea",
    type: "Signaturs product",
    image: "images/greentea.png",
    price: 26,
    size: 500,
    id: 2,
    numberItemInCart: 1,
    cartFlag: false,
  ),
  DataModel(
    name: "Cappucci",
    type: "Signaturs product",
    image: "images/greentea.png",
    price: 24,
    size: 500,
    id: 3,
    numberItemInCart: 1,
    cartFlag: false,
  ),
  DataModel(
    name: "Cafe Latte",
    type: "Signaturs product",
    image: "images/greentea.png",
    price: 32,
    size: 500,
    id: 4,
    numberItemInCart: 1,
    cartFlag: false,
  ),
  DataModel(
    name: "Bruce Coffee",
    type: "Signaturs product",
    image: "images/greentea.png",
    price: 18,
    size: 500,
    id: 5,
    numberItemInCart: 1,
    cartFlag: false,
  ),
  DataModel(
    name: "Green tea",
    type: "Signaturs product",
    image: "images/greentea.png",
    price: 36,
    size: 500,
    id: 6,
    numberItemInCart: 1,
    cartFlag: false,
  ),
  DataModel(
    name: "Rose tea",
    type: "Signaturs product",
    image: "images/greentea.png",
    price: 24,
    size: 500,
    id: 7,
    numberItemInCart: 1,
    cartFlag: false,
  ),
  DataModel(
    name: "Jasmine tea",
    type: "Signaturs product",
    image: "images/greentea.png",
    price: 26,
    size: 500,
    id: 8,
    numberItemInCart: 1,
    cartFlag: false,
  ),
  DataModel(
    name: "Cappucci",
    type: "Signaturs product",
    image: "images/greentea.png",
    price: 24,
    size: 500,
    id: 9,
    numberItemInCart: 1,
    cartFlag: false,
  ),
  DataModel(
    name: "Cafe Latte",
    type: "Signaturs product",
    image: "images/greentea.png",
    price: 32,
    size: 500,
    id: 10,
    numberItemInCart: 1,
    cartFlag: false,
  ),
  DataModel(
    name: "Bruce Coffee",
    type: "Signaturs product",
    image: "images/greentea.png",
    price: 18,
    size: 500,
    id: 11,
    numberItemInCart: 1,
    cartFlag: false,
  ),
];
